import { PatientPhysiology } from './types';

export const patients: PatientPhysiology[] = [
  {
    id: 'healthy',
    name: 'Healthy Adult (70kg)',
    description: 'Normal lung mechanics, no pathology',
    weight: 70,
    compliance: 50,
    resistance: 5,
    frc: 2400,
    spontaneousRate: 0,
    spontaneousTidalVolume: 0,
    baseHR: 72,
    baseSBP: 120,
    baseDBP: 75,
    baseSpO2: 99,
    baseEtCO2: 38,
    optimalTV: 490,
    optimalRR: 14,
    optimalPEEP: 5,
    optimalFiO2: 0.4,
    optimalPS: 10,
  },
  {
    id: 'obese',
    name: 'Morbidly Obese (140kg)',
    description: 'Reduced compliance, increased resistance, high BMI',
    weight: 140,
    compliance: 25,
    resistance: 12,
    frc: 1600,
    spontaneousRate: 0,
    spontaneousTidalVolume: 0,
    baseHR: 88,
    baseSBP: 145,
    baseDBP: 90,
    baseSpO2: 94,
    baseEtCO2: 42,
    optimalTV: 420,
    optimalRR: 16,
    optimalPEEP: 10,
    optimalFiO2: 0.5,
    optimalPS: 14,
  },
  {
    id: 'ards',
    name: 'ARDS Patient',
    description: 'Very low compliance, requires protective ventilation (6mL/kg)',
    weight: 70,
    compliance: 15,
    resistance: 8,
    frc: 1200,
    spontaneousRate: 0,
    spontaneousTidalVolume: 0,
    baseHR: 110,
    baseSBP: 100,
    baseDBP: 60,
    baseSpO2: 88,
    baseEtCO2: 45,
    optimalTV: 350,
    optimalRR: 22,
    optimalPEEP: 14,
    optimalFiO2: 0.8,
    optimalPS: 12,
  },
  {
    id: 'bronchospasm',
    name: 'Severe Bronchospasm',
    description: 'Very high resistance, normal compliance, risk of air trapping',
    weight: 70,
    compliance: 50,
    resistance: 28,
    frc: 3200,
    spontaneousRate: 0,
    spontaneousTidalVolume: 0,
    baseHR: 115,
    baseSBP: 135,
    baseDBP: 85,
    baseSpO2: 91,
    baseEtCO2: 50,
    optimalTV: 450,
    optimalRR: 10,
    optimalPEEP: 5,
    optimalFiO2: 0.5,
    optimalPS: 10,
  },
  {
    id: 'restrictive',
    name: 'Restrictive Lung Disease',
    description: 'Low compliance, normal resistance, small tidal volumes needed',
    weight: 65,
    compliance: 20,
    resistance: 5,
    frc: 1500,
    spontaneousRate: 0,
    spontaneousTidalVolume: 0,
    baseHR: 92,
    baseSBP: 125,
    baseDBP: 78,
    baseSpO2: 93,
    baseEtCO2: 40,
    optimalTV: 350,
    optimalRR: 20,
    optimalPEEP: 6,
    optimalFiO2: 0.5,
    optimalPS: 10,
  },
  {
    id: 'spontaneous',
    name: 'Spontaneously Breathing (Inadequate)',
    description: 'Breathing spontaneously but with poor rate and volumes, needs support',
    weight: 70,
    compliance: 40,
    resistance: 6,
    frc: 2200,
    spontaneousRate: 8,
    spontaneousTidalVolume: 200,
    baseHR: 105,
    baseSBP: 110,
    baseDBP: 65,
    baseSpO2: 89,
    baseEtCO2: 55,
    optimalTV: 450,
    optimalRR: 14,
    optimalPEEP: 5,
    optimalFiO2: 0.4,
    optimalPS: 12,
  },
];

export function getDefaultSettings(patient: PatientPhysiology) {
  return {
    mode: 'VCV' as const,
    tidalVolume: 500,
    respiratoryRate: 14,
    peep: 5,
    fio2: 0.4,
    ieRatio: 2,
    pressureSupport: 10,
    pInsp: 15,
    pHigh: 25,
    pLow: 0,
    tHigh: 4,
    tLow: 0.5,
    flowRate: 40,
    pMax: 35,
    inspiratoryTime: 1.0,
  };
}
